[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  VITE_SUPABASE_URL = "https://goudraupaciortdvyqlh.supabase.co"
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdvdWRyYXVwYWNpb3J0ZHZ5cWxoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyMTA2MzMsImV4cCI6MjA1OTc4NjYzM30.-eyJ_x2W4_N5uTBo8deghAtOvyqN7ONAsgC3swPE-9Q"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200